# Service to expose frontend service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-app.fullname" . }}-frontend
  labels:
    {{- include "payment-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend