# templates/configmap-common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment-app.fullname" . }}-common-code
  labels:
    {{- include "payment-app.labels" . | nindent 4 }}
data:
  {{- $files := .Files.Glob "../../backend/common/*" }}
  {{- range $path, $_ := $files }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}