# Ingress configuration for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "payment-app.fullname" . }}
  labels:
    {{- include "payment-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-{{ .service }}
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}