apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment-app.fullname" . }}-secret
  labels:
    {{- include "payment-app.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.auth.jwtSecret | b64enc }}